project_id: 302994
api_token: 90c94c6aa5fb02574320b67fbff124ab87a33b1d959ea4afd627a75c4799d8a4f351fe14df1020df
preserve_hierarchy: true

languages_mapping: &languages_mapping
  locale:
    'es-ES': 'es'
    'fr': 'fr'
    'id': 'id'
    'it': 'it'
    'ja': 'ja'
    'ko': 'ko'
    'pt-BR': 'pt'
    'ru': 'ru'
    'tr': 'tr'
    'zh-CN': 'zh'
    'zh-TW': 'zh-TW'

files:
  -
    source: '/docs/**/*'
    translation: '/i18n/%locale%/docusaurus-plugin-content-docs/current/**/%original_file_name%'
    languages_mapping: *languages_mapping
  -
    source: '/i18n/en/**/*'
    translation: '/i18n/%locale%/**/%original_file_name%'
    languages_mapping: *languages_mapping
  -
    source: '/blog/**/*'
    translation: '/i18n/%locale%/docusaurus-plugin-content-blog/**/%original_file_name%'
    languages_mapping: *languages_mapping
  -
    source: '/versioned_docs/**/*'
    translation: '/i18n/%locale%/docusaurus-plugin-content-docs/**/%original_file_name%'
    languages_mapping: *languages_mapping
